/*
Fermyon Cloud API

Testing RegistryApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package cloud_openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/fermyon/cloud-openapi"
)

func Test_cloud_openapi_RegistryApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RegistryApiService ApiRegistryIBindleNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bindleName string

		httpRes, err := apiClient.RegistryApi.ApiRegistryIBindleNameGet(context.Background(), bindleName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegistryApiService ApiRegistryIBindleNamePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bindleName string

		httpRes, err := apiClient.RegistryApi.ApiRegistryIBindleNamePost(context.Background(), bindleName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegistryApiService ApiRegistryIPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.RegistryApi.ApiRegistryIPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
