/*
Fermyon Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_openapi

import (
	"encoding/json"
)

// checks if the PatchAccountDetailsCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchAccountDetailsCommand{}

// PatchAccountDetailsCommand struct for PatchAccountDetailsCommand
type PatchAccountDetailsCommand struct {
	IsMarketingEmailOn *BooleanField `json:"isMarketingEmailOn,omitempty"`
}

// NewPatchAccountDetailsCommand instantiates a new PatchAccountDetailsCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchAccountDetailsCommand() *PatchAccountDetailsCommand {
	this := PatchAccountDetailsCommand{}
	return &this
}

// NewPatchAccountDetailsCommandWithDefaults instantiates a new PatchAccountDetailsCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchAccountDetailsCommandWithDefaults() *PatchAccountDetailsCommand {
	this := PatchAccountDetailsCommand{}
	return &this
}

// GetIsMarketingEmailOn returns the IsMarketingEmailOn field value if set, zero value otherwise.
func (o *PatchAccountDetailsCommand) GetIsMarketingEmailOn() BooleanField {
	if o == nil || IsNil(o.IsMarketingEmailOn) {
		var ret BooleanField
		return ret
	}
	return *o.IsMarketingEmailOn
}

// GetIsMarketingEmailOnOk returns a tuple with the IsMarketingEmailOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchAccountDetailsCommand) GetIsMarketingEmailOnOk() (*BooleanField, bool) {
	if o == nil || IsNil(o.IsMarketingEmailOn) {
		return nil, false
	}
	return o.IsMarketingEmailOn, true
}

// HasIsMarketingEmailOn returns a boolean if a field has been set.
func (o *PatchAccountDetailsCommand) HasIsMarketingEmailOn() bool {
	if o != nil && !IsNil(o.IsMarketingEmailOn) {
		return true
	}

	return false
}

// SetIsMarketingEmailOn gets a reference to the given BooleanField and assigns it to the IsMarketingEmailOn field.
func (o *PatchAccountDetailsCommand) SetIsMarketingEmailOn(v BooleanField) {
	o.IsMarketingEmailOn = &v
}

func (o PatchAccountDetailsCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchAccountDetailsCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsMarketingEmailOn) {
		toSerialize["isMarketingEmailOn"] = o.IsMarketingEmailOn
	}
	return toSerialize, nil
}

type NullablePatchAccountDetailsCommand struct {
	value *PatchAccountDetailsCommand
	isSet bool
}

func (v NullablePatchAccountDetailsCommand) Get() *PatchAccountDetailsCommand {
	return v.value
}

func (v *NullablePatchAccountDetailsCommand) Set(val *PatchAccountDetailsCommand) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchAccountDetailsCommand) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchAccountDetailsCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchAccountDetailsCommand(val *PatchAccountDetailsCommand) *NullablePatchAccountDetailsCommand {
	return &NullablePatchAccountDetailsCommand{value: val, isSet: true}
}

func (v NullablePatchAccountDetailsCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchAccountDetailsCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


