/*
Fermyon Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_openapi

import (
	"encoding/json"
)

// checks if the AppDomainItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppDomainItem{}

// AppDomainItem struct for AppDomainItem
type AppDomainItem struct {
	Name string `json:"name"`
	ValidationStatus DomainValidationStatus `json:"validationStatus"`
}

// NewAppDomainItem instantiates a new AppDomainItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppDomainItem(name string, validationStatus DomainValidationStatus) *AppDomainItem {
	this := AppDomainItem{}
	this.Name = name
	this.ValidationStatus = validationStatus
	return &this
}

// NewAppDomainItemWithDefaults instantiates a new AppDomainItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppDomainItemWithDefaults() *AppDomainItem {
	this := AppDomainItem{}
	return &this
}

// GetName returns the Name field value
func (o *AppDomainItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AppDomainItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AppDomainItem) SetName(v string) {
	o.Name = v
}

// GetValidationStatus returns the ValidationStatus field value
func (o *AppDomainItem) GetValidationStatus() DomainValidationStatus {
	if o == nil {
		var ret DomainValidationStatus
		return ret
	}

	return o.ValidationStatus
}

// GetValidationStatusOk returns a tuple with the ValidationStatus field value
// and a boolean to check if the value has been set.
func (o *AppDomainItem) GetValidationStatusOk() (*DomainValidationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidationStatus, true
}

// SetValidationStatus sets field value
func (o *AppDomainItem) SetValidationStatus(v DomainValidationStatus) {
	o.ValidationStatus = v
}

func (o AppDomainItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppDomainItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["validationStatus"] = o.ValidationStatus
	return toSerialize, nil
}

type NullableAppDomainItem struct {
	value *AppDomainItem
	isSet bool
}

func (v NullableAppDomainItem) Get() *AppDomainItem {
	return v.value
}

func (v *NullableAppDomainItem) Set(val *AppDomainItem) {
	v.value = val
	v.isSet = true
}

func (v NullableAppDomainItem) IsSet() bool {
	return v.isSet
}

func (v *NullableAppDomainItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppDomainItem(val *AppDomainItem) *NullableAppDomainItem {
	return &NullableAppDomainItem{value: val, isSet: true}
}

func (v NullableAppDomainItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppDomainItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


