/*
Fermyon Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_openapi

import (
	"encoding/json"
)

// checks if the DeleteSqlDatabaseCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteSqlDatabaseCommand{}

// DeleteSqlDatabaseCommand struct for DeleteSqlDatabaseCommand
type DeleteSqlDatabaseCommand struct {
	Name string `json:"name"`
}

// NewDeleteSqlDatabaseCommand instantiates a new DeleteSqlDatabaseCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteSqlDatabaseCommand(name string) *DeleteSqlDatabaseCommand {
	this := DeleteSqlDatabaseCommand{}
	this.Name = name
	return &this
}

// NewDeleteSqlDatabaseCommandWithDefaults instantiates a new DeleteSqlDatabaseCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteSqlDatabaseCommandWithDefaults() *DeleteSqlDatabaseCommand {
	this := DeleteSqlDatabaseCommand{}
	return &this
}

// GetName returns the Name field value
func (o *DeleteSqlDatabaseCommand) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeleteSqlDatabaseCommand) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeleteSqlDatabaseCommand) SetName(v string) {
	o.Name = v
}

func (o DeleteSqlDatabaseCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteSqlDatabaseCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableDeleteSqlDatabaseCommand struct {
	value *DeleteSqlDatabaseCommand
	isSet bool
}

func (v NullableDeleteSqlDatabaseCommand) Get() *DeleteSqlDatabaseCommand {
	return v.value
}

func (v *NullableDeleteSqlDatabaseCommand) Set(val *DeleteSqlDatabaseCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteSqlDatabaseCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteSqlDatabaseCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteSqlDatabaseCommand(val *DeleteSqlDatabaseCommand) *NullableDeleteSqlDatabaseCommand {
	return &NullableDeleteSqlDatabaseCommand{value: val, isSet: true}
}

func (v NullableDeleteSqlDatabaseCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteSqlDatabaseCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


