/*
Fermyon Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_openapi

import (
	"encoding/json"
)

// checks if the PersonalAccessTokenValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PersonalAccessTokenValue{}

// PersonalAccessTokenValue struct for PersonalAccessTokenValue
type PersonalAccessTokenValue struct {
	Name *string `json:"name,omitempty"`
	Token *string `json:"token,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewPersonalAccessTokenValue instantiates a new PersonalAccessTokenValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPersonalAccessTokenValue() *PersonalAccessTokenValue {
	this := PersonalAccessTokenValue{}
	return &this
}

// NewPersonalAccessTokenValueWithDefaults instantiates a new PersonalAccessTokenValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonalAccessTokenValueWithDefaults() *PersonalAccessTokenValue {
	this := PersonalAccessTokenValue{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PersonalAccessTokenValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalAccessTokenValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PersonalAccessTokenValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PersonalAccessTokenValue) SetName(v string) {
	o.Name = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *PersonalAccessTokenValue) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalAccessTokenValue) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *PersonalAccessTokenValue) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *PersonalAccessTokenValue) SetToken(v string) {
	o.Token = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PersonalAccessTokenValue) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonalAccessTokenValue) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PersonalAccessTokenValue) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PersonalAccessTokenValue) SetId(v string) {
	o.Id = &v
}

func (o PersonalAccessTokenValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PersonalAccessTokenValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullablePersonalAccessTokenValue struct {
	value *PersonalAccessTokenValue
	isSet bool
}

func (v NullablePersonalAccessTokenValue) Get() *PersonalAccessTokenValue {
	return v.value
}

func (v *NullablePersonalAccessTokenValue) Set(val *PersonalAccessTokenValue) {
	v.value = val
	v.isSet = true
}

func (v NullablePersonalAccessTokenValue) IsSet() bool {
	return v.isSet
}

func (v *NullablePersonalAccessTokenValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersonalAccessTokenValue(val *PersonalAccessTokenValue) *NullablePersonalAccessTokenValue {
	return &NullablePersonalAccessTokenValue{value: val, isSet: true}
}

func (v NullablePersonalAccessTokenValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersonalAccessTokenValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


