/*
Fermyon Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_openapi

import (
	"encoding/json"
)

// checks if the CreatePersonalAccessTokenCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePersonalAccessTokenCommand{}

// CreatePersonalAccessTokenCommand struct for CreatePersonalAccessTokenCommand
type CreatePersonalAccessTokenCommand struct {
	Name string `json:"name"`
}

// NewCreatePersonalAccessTokenCommand instantiates a new CreatePersonalAccessTokenCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePersonalAccessTokenCommand(name string) *CreatePersonalAccessTokenCommand {
	this := CreatePersonalAccessTokenCommand{}
	this.Name = name
	return &this
}

// NewCreatePersonalAccessTokenCommandWithDefaults instantiates a new CreatePersonalAccessTokenCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePersonalAccessTokenCommandWithDefaults() *CreatePersonalAccessTokenCommand {
	this := CreatePersonalAccessTokenCommand{}
	return &this
}

// GetName returns the Name field value
func (o *CreatePersonalAccessTokenCommand) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreatePersonalAccessTokenCommand) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreatePersonalAccessTokenCommand) SetName(v string) {
	o.Name = v
}

func (o CreatePersonalAccessTokenCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePersonalAccessTokenCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableCreatePersonalAccessTokenCommand struct {
	value *CreatePersonalAccessTokenCommand
	isSet bool
}

func (v NullableCreatePersonalAccessTokenCommand) Get() *CreatePersonalAccessTokenCommand {
	return v.value
}

func (v *NullableCreatePersonalAccessTokenCommand) Set(val *CreatePersonalAccessTokenCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePersonalAccessTokenCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePersonalAccessTokenCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePersonalAccessTokenCommand(val *CreatePersonalAccessTokenCommand) *NullableCreatePersonalAccessTokenCommand {
	return &NullableCreatePersonalAccessTokenCommand{value: val, isSet: true}
}

func (v NullableCreatePersonalAccessTokenCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePersonalAccessTokenCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


