/*
Fermyon Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_openapi

import (
	"encoding/json"
)

// checks if the StringField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StringField{}

// StringField struct for StringField
type StringField struct {
	Value *string `json:"value,omitempty"`
}

// NewStringField instantiates a new StringField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStringField() *StringField {
	this := StringField{}
	return &this
}

// NewStringFieldWithDefaults instantiates a new StringField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStringFieldWithDefaults() *StringField {
	this := StringField{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *StringField) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StringField) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *StringField) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *StringField) SetValue(v string) {
	o.Value = &v
}

func (o StringField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StringField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableStringField struct {
	value *StringField
	isSet bool
}

func (v NullableStringField) Get() *StringField {
	return v.value
}

func (v *NullableStringField) Set(val *StringField) {
	v.value = val
	v.isSet = true
}

func (v NullableStringField) IsSet() bool {
	return v.isSet
}

func (v *NullableStringField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStringField(val *StringField) *NullableStringField {
	return &NullableStringField{value: val, isSet: true}
}

func (v NullableStringField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStringField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


