/*
Fermyon Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_openapi

import (
	"encoding/json"
)

// checks if the BooleanField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BooleanField{}

// BooleanField struct for BooleanField
type BooleanField struct {
	Value *bool `json:"value,omitempty"`
}

// NewBooleanField instantiates a new BooleanField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBooleanField() *BooleanField {
	this := BooleanField{}
	return &this
}

// NewBooleanFieldWithDefaults instantiates a new BooleanField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBooleanFieldWithDefaults() *BooleanField {
	this := BooleanField{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *BooleanField) GetValue() bool {
	if o == nil || IsNil(o.Value) {
		var ret bool
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BooleanField) GetValueOk() (*bool, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *BooleanField) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given bool and assigns it to the Value field.
func (o *BooleanField) SetValue(v bool) {
	o.Value = &v
}

func (o BooleanField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BooleanField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableBooleanField struct {
	value *BooleanField
	isSet bool
}

func (v NullableBooleanField) Get() *BooleanField {
	return v.value
}

func (v *NullableBooleanField) Set(val *BooleanField) {
	v.value = val
	v.isSet = true
}

func (v NullableBooleanField) IsSet() bool {
	return v.isSet
}

func (v *NullableBooleanField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBooleanField(val *BooleanField) *NullableBooleanField {
	return &NullableBooleanField{value: val, isSet: true}
}

func (v NullableBooleanField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBooleanField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


