/*
Fermyon Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloud_openapi

import (
	"encoding/json"
	"time"
)

// checks if the AccountDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountDetails{}

// AccountDetails struct for AccountDetails
type AccountDetails struct {
	Plan *AccountPlanRecord `json:"plan,omitempty"`
	IsMarketingEmailOn *bool `json:"isMarketingEmailOn,omitempty"`
	CreatedAt NullableTime `json:"createdAt,omitempty"`
}

// NewAccountDetails instantiates a new AccountDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountDetails() *AccountDetails {
	this := AccountDetails{}
	return &this
}

// NewAccountDetailsWithDefaults instantiates a new AccountDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountDetailsWithDefaults() *AccountDetails {
	this := AccountDetails{}
	return &this
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *AccountDetails) GetPlan() AccountPlanRecord {
	if o == nil || IsNil(o.Plan) {
		var ret AccountPlanRecord
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountDetails) GetPlanOk() (*AccountPlanRecord, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *AccountDetails) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given AccountPlanRecord and assigns it to the Plan field.
func (o *AccountDetails) SetPlan(v AccountPlanRecord) {
	o.Plan = &v
}

// GetIsMarketingEmailOn returns the IsMarketingEmailOn field value if set, zero value otherwise.
func (o *AccountDetails) GetIsMarketingEmailOn() bool {
	if o == nil || IsNil(o.IsMarketingEmailOn) {
		var ret bool
		return ret
	}
	return *o.IsMarketingEmailOn
}

// GetIsMarketingEmailOnOk returns a tuple with the IsMarketingEmailOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountDetails) GetIsMarketingEmailOnOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMarketingEmailOn) {
		return nil, false
	}
	return o.IsMarketingEmailOn, true
}

// HasIsMarketingEmailOn returns a boolean if a field has been set.
func (o *AccountDetails) HasIsMarketingEmailOn() bool {
	if o != nil && !IsNil(o.IsMarketingEmailOn) {
		return true
	}

	return false
}

// SetIsMarketingEmailOn gets a reference to the given bool and assigns it to the IsMarketingEmailOn field.
func (o *AccountDetails) SetIsMarketingEmailOn(v bool) {
	o.IsMarketingEmailOn = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccountDetails) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccountDetails) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AccountDetails) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *AccountDetails) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}
// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *AccountDetails) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *AccountDetails) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

func (o AccountDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	if !IsNil(o.IsMarketingEmailOn) {
		toSerialize["isMarketingEmailOn"] = o.IsMarketingEmailOn
	}
	if o.CreatedAt.IsSet() {
		toSerialize["createdAt"] = o.CreatedAt.Get()
	}
	return toSerialize, nil
}

type NullableAccountDetails struct {
	value *AccountDetails
	isSet bool
}

func (v NullableAccountDetails) Get() *AccountDetails {
	return v.value
}

func (v *NullableAccountDetails) Set(val *AccountDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountDetails(val *AccountDetails) *NullableAccountDetails {
	return &NullableAccountDetails{value: val, isSet: true}
}

func (v NullableAccountDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


